In [1]:
import numpy as np

In [2]:
y_predicted=np.array([1,1,0,0,1])
y_true=np.array([0.30,0.7,1,0,0.5])

In [3]:
np.log([1])

array([0.])

In [4]:
np.log([0.00000001])

array([-18.42068074])

In [5]:
eplison = 1e-15

In [6]:
y_predicted

array([1, 1, 0, 0, 1])

In [7]:
y_predicted_new = [max(i,eplison) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [8]:
y_predicted_new = [max(i,1-eplison) for i in y_predicted]
y_predicted_new

[1, 1, 0.999999999999999, 0.999999999999999, 1]

In [9]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([ 0.00000000e+00,  0.00000000e+00, -9.99200722e-16, -9.99200722e-16,
        0.00000000e+00])

### Formulae

In [10]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

/tmp/ipykernel_88958/146511816.py:1: RuntimeWarning: divide by zero encountered in log
  -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))


inf

In [14]:
def log_loss(y_true,y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-eplison) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [15]:
log_loss(y_true,y_predicted)

17.2696280766844