In [17]:
import numpy as np

In [18]:
predicted=np.array([1,1,0,0,1])
actuals=np.array([0.30,0.7,1,0,0.5])

In [19]:
np.log([1])

array([0.])

In [20]:
np.log([0.00000001])

array([-18.42068074])

In [21]:
eplison = 1e-15

In [22]:
predicted

array([1, 1, 0, 0, 1])

In [23]:
predicted_new = [max(i,eplison) for i in predicted]
predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [24]:
predicted_new = [max(i,1-eplison) for i in predicted]
predicted_new

[1, 1, 0.999999999999999, 0.999999999999999, 1]

In [25]:
predicted_new = np.array(predicted_new)
np.log(predicted_new)

array([ 0.00000000e+00,  0.00000000e+00, -9.99200722e-16, -9.99200722e-16,
        0.00000000e+00])

### Formulae

In [26]:
-np.mean(actuals*np.log(predicted_new)+(1-actuals)*np.log(1-predicted_new))

/tmp/ipykernel_238289/1238841621.py:1: RuntimeWarning: divide by zero encountered in log
  -np.mean(actuals*np.log(predicted_new)+(1-actuals)*np.log(1-predicted_new))


inf